artifacts:
  - path: Trial Application\bin\Release\Trial Application.exe
    name: Trial Application

deploy:
  release: application-v$(appveyor_build_version)
  description: 'Release v$(appveyor_build_version)'
  provider: GitHub
  auth_token: $(github_access_token) # your encrypted token from GitHub
  artifact: /.*\.exe/
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
